import Head from "next/head";
import React from "react";
import { getProduct } from "../../api_service/product";
import Card from "../../components/utils/Card";
import { setProduct, getProductState } from "../../redux/slice/productSlice";
import { wrapper } from "../../redux/store";
import { useAppSelector } from "../../redux/hook";
import { checkServerSideAuth } from '../../utils/serversideAuthentication';

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async (ctx) => {
    
    checkServerSideAuth(ctx, store);

    const params = { categoryId: 2 }; // it is youtube categoryId
    const res = await getProduct(params);
    const data = {
      product: res,
      actionType: "getAll",
    };
    store.dispatch(setProduct(data));
    return {
      props: {},
    };
  }
);

type Props = {};

const index = (props: Props) => {
  const { product } = useAppSelector(getProductState);
 
  return (
    <div className="container mx-auto">
      <Head>
        <title>Sell Tool - Youtube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-lg lg:text-xl font-semibold mt-4">
          Tools For Youtube
        </h1>

        {/* Demo Some Tools */}

        <div className="mt-4 grid grid-cols-2 md:grid-cols-4 xl:grid-cols-6 gap-4">
          {product.length === 0 ? (
            <h1>No data</h1>
          ) : (
            <>
              {product.map((singleProduct: any) => (
                <Card product={singleProduct} key={singleProduct.id} />
              ))}
            </>
          )}
        </div>
      </main>
    </div>
  );
};

export default index;
