import Head from "next/head";
import Button from "../../components/utils/Button";
import { useState } from "react";
import Link from "next/link";
import { BsArrowRight } from "react-icons/bs";
import { login } from "../../api_service/auth";
import { setAuth, getAuthData, setLoading } from "../../redux/slice/authSlice";
import { useDispatch } from "react-redux";
import { useRouter } from "next/router";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export default function Login() {
  const router = useRouter();
  const dispatch = useDispatch();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [loading, setLoading] = useState(false);

  const signin = async () => {
    setLoading(true);
    const response = await login(email, password);
    if (response?.status === 201) {
      dispatch(setAuth(response.data));
      if (response.data.role.name === "Admin") {
        router.push("/admin/dashboard");
      } else {
        router.push("/");
      }
    } else {
      toast.error(response);
    }
    setLoading(false);
  };

  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto">
        <ToastContainer />
        <div className="w-[80%] lg:w-[50%]  mx-auto">
          <h1 className="my-4 text-lg font-bold">Sign In</h1>
          <input
            type="text"
            placeholder="Email..."
            className=" border bg-transparent mt-2  px-4 py-2 rounded-lg w-full"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
          />
          <input
            type="password"
            placeholder="Password..."
            className=" border bg-transparent mt-2  px-4 py-2 rounded-lg w-full"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
          <div className="mt-4">
            {loading ? (
              <Button text="Loading..." action={() => {}} />
            ) : (
              <Button text="Login" action={signin} />
            )}
          </div>

          <Link href={"/auth/signup"}>
            <div className="flex items-center mt-4 cursor-pointer  w-20 text-blue-600">
              <p className="hover:underline">Sign Up</p>
              <BsArrowRight className="ml-2" />
            </div>
          </Link>
        </div>
      </main>
    </div>
  );
}
