import Head from "next/head";
import Button from "../../components/utils/Button";
import { useState } from "react";
import Link from "next/link";
import { BsArrowLeft, BsArrowRight } from "react-icons/bs";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { register } from "../../api_service/auth/index";
import { useRouter } from "next/router";

export default function Login() {
  const router = useRouter();
  const [file, setFile] = useState<File | null>(null);
  const [fullname, setFullname] = useState("");
  const [gender, setGender] = useState("1");
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");

  const signUp = async () => {
    if (
      !fullname ||
      !gender ||
      !email ||
      !phone ||
      !password ||
      !confirmPassword
    ) {
      toast.warning("All is requeired !");
      return;
    }

    if (password !== confirmPassword) {
      toast.warning("Password and Confirm Password Not Match !");
      return;
    }
    const data = {
      full_name: fullname,
      gender: gender.toString(),
      email: email,
      phone_number: phone,
      password: password,
      role_id: "2",
      image: file,
    };
    const res = await register(data);
    if (res.status === 201) {
      toast.success("Registerd");
      router.push("/auth/login");
    } else {
      toast.error(res);
    }
  };

  return (
    <div>
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto">
        <ToastContainer />
        <div className="w-[80%] lg:w-[50%]  mx-auto">
          <h1 className="my-4 text-lg font-bold">Sign Up</h1>

          <input
            type="file"
            className="mt-2"
            onChange={(e) => setFile(e.target.files![0])}
          />
          <input
            type="text"
            placeholder="Full Name..."
            className=" border bg-transparent mt-2  px-4 py-2 rounded-lg w-full"
            value={fullname}
            onChange={(e) => setFullname(e.target.value)}
          />
          <select
            className=" border bg-transparent mt-2  px-4 py-2 rounded-lg w-full"
            value={gender}
            onChange={(e) => setGender(e.target.value)}
          >
            <option value="1">Male</option>
            <option value="2">Female</option>
          </select>
          <input
            type="text"
            placeholder="Phone Number..."
            className=" border bg-transparent mt-2  px-4 py-2 rounded-lg w-full"
            value={phone}
            onChange={(e) => setPhone(e.target.value)}
          />
          <input
            type="email"
            placeholder="Email..."
            className=" border bg-transparent mt-2  px-4 py-2 rounded-lg w-full"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
          />
          <input
            type="password"
            placeholder="Password..."
            className=" border bg-transparent mt-2  px-4 py-2 rounded-lg w-full"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />

          <input
            type="password"
            placeholder="Confirm Password..."
            className=" border bg-transparent mt-2  px-4 py-2 rounded-lg w-full"
            value={confirmPassword}
            onChange={(e) => setConfirmPassword(e.target.value)}
          />
          <div className="mt-4">
            <Button text="Sign Up" action={signUp} />
          </div>

          <Link href={"/auth/login"}>
            <div className="flex items-center mt-4 cursor-pointer w-20 hover:underline text-blue-500">
              <BsArrowLeft className="mr-2" />
              <p>Login</p>
            </div>
          </Link>
        </div>
      </main>
    </div>
  );
}
