import type { NextPage } from "next";
import Head from "next/head";
import Card from "../components/utils/Card";
import { getProduct } from "../api_service/product";
import { wrapper } from "../redux/store";
import { setProduct, getProductState } from "../redux/slice/productSlice";
import { useAppSelector } from "../redux/hook";
import { checkServerSideAuth } from "../utils/serversideAuthentication";
import { motion as m } from "framer-motion";
import Button from "../components/utils/Button";

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async (ctx) => {
    checkServerSideAuth(ctx, store);
    const res = await getProduct({});
    const data = {
      product: res,
      actionType: "getAll",
    };
    store.dispatch(setProduct(data));
    return {
      props: {},
    };
  }
);

const Home: NextPage = (props) => {
  const { product } = useAppSelector(getProductState);
  return (
    <div >
      <Head>
        <title>Sell Tool - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div
          className={`h-[100vh] flex justify-center items-center flex-col w-full bg-[url('../images/mainbg.jpg')] bg-cover bg-center`}
        >
          <div className="text-center">
            <m.div
              initial={{
                x: -30,
                opacity: 0,
              }}
              animate={{
                x: 0,
                opacity: 1,
              }}
              transition={{
                duration: 0.75,
              }}
              exit={{
                x: 0,
                opacity: 1,
              }}
            >
              <h1 className="text-2xl md:text-4xl lg:text-7xl font-bold text-white">
                Find Your <span className="text-cyan-500">Tool</span> Here
              </h1>
            </m.div>

            <m.div
              initial={{
                x: 30,
                opacity: 0,
              }}
              animate={{
                x: 0,
                opacity: 1,
              }}
              transition={{
                duration: 0.75,
              }}
              exit={{
                x: 0,
                opacity: 1,
              }}
            >
              <p className="mt-2 text-white text-lg">
                Use your free time to earn more money with our tools.
              </p>
            </m.div>

            <m.div
              initial={{
                y: 30,
                opacity: 0,
              }}
              animate={{
                y: 0,
                opacity: 1,
              }}
              transition={{
                duration: 0.75,
              }}
              exit={{
                y: 0,
                opacity: 1,
              }}
            >
              <div className="mt-4">
              <Button text="Find Now" action={() => {}}/>
              </div>
            </m.div>
          </div>
        </div>

        {/* Demo Some Tools */}

        <div className=" container mx-auto ">
          <h1 className="mt-4 font-semibold text-2xl">Recent Tools</h1>

          <div className="mt-4 grid grid-cols-2 md:grid-cols-4 xl:grid-cols-6 gap-4">
            {product?.length === 0 ? (
              <h1>No data</h1>
            ) : (
              <>
                {product?.map((singleProduct: any) => (
                  <Card key={singleProduct.id} product={singleProduct} />
                ))}
              </>
            )}
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
